<?php

namespace AppBundle\Repository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllLinksFromProject($project_id)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT l, project
                FROM AppBundle:Link l
                JOIN l.projects project
                WHERE project.id = :id'
        )->setParameter('id', $project_id);
        return $query->getResult();
    }
}
