<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllProjectsFromPath($path_id){
        $query = $this->getEntityManager()->createQuery(
            'SELECT p, path
                  FROM AppBundle:Project p
                  JOIN p.paths path
                  WHERE path.id= :id'
        )->setParameter('id', $path_id);
        return $query->getResult();
    }
}
